### ISSUE TITLE
Pypi github URL is wrong

### ISSUE THREAD

**Issue by pganssle** [Michsior14/ndb_adapter#1]
On [Pypi](https://pypi.python.org/pypi/ndb_adapter/1.0), the url is pointing to `nba_adapter`. Probably you just need to update it in [`setup.py`](https://github.com/Michsior14/NDBAdapter/blob/master/setup.py#L14), though I suppose you could rename the project on github insteadl

**Comment by Michsior14** [comment]
Thanks, fixed :)
